version: '3'
services:

  nginx:
     image: 'jc21/nginx-proxy-manager:latest'
     restart: unless-stopped
     ports:
       - '80:80'
       - '81:81'
       - '443:443'
       - '8070-8080:8070-8080'
     volumes:
       - nginx:/data
       - ./data/letsencrypt/letsencrypt:/etc/letsencrypt

  api:
    image: 'norbye93/api:latest'
    container_name: 'api'
    restart: 'unless-stopped'
    ports:
      - "8090:8090"
    volumes:
      - api:/api
    depends_on:
      - db
    env_file:
      - .env.api

  db:
   image: postgres:latest
   volumes:
     - postgres:/mydatabase
  #  ports:
  #    - "5432:5432"
   restart: always
   environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}

  mosquitto:
   image: eclipse-mosquitto:latest
   container_name: mosquitto
   ports:
     - "1883:1883"
     - "9001:9001"
   volumes:
     - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
     - ./data/mosquitto/passwd:/mosquitto/config/passwd

  influxdb:
   image: influxdb:latest
   privileged: true
   container_name: influxdb
   restart: always
   ports:
     - "8086"
   volumes:
     - influxdb:/var/lib/influxdb2
     - influxdb:/etc/influxdb2
   environment:
     - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
     - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
     - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
     - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
     - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}


  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

    
volumes:
  influxdb:
  telegraf:
  nginx:
  api:
  postgres: